# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: FAIR Data 101 Express
email: contact@ardc.edu.au
description: >- # this means to ignore newlines until "baseurl:"
  FAIR Data 101 Express is a four week course that gives an introduction to the FAIR principles.
baseurl: "/FAIR-data-101-training" # the subpath of your site, e.g. /blog
url: "https://au-research.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ARDC_AU
github_username:  au-research
# Build settings
theme: minima

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - README.md
  - 1-findable/quiz.md
  - 2-accessible/quiz.md
  - 3-interoperable/quiz.md
  - 4-reusable/quiz.md    
#   - gemfiles/
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
   -
    scope:
      path: ''
    values:
      author: ARDC
      layout: page 
